version: '2'
services:
    jhipstersampleapplicationmongo-app:
        image: jhipstersampleapplicationmongo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipstersampleapplicationmongo-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterSampleApplicationMongo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplicationmongo-mongodb:
        extends:
            file: mongodb.yml
            service: jhipstersampleapplicationmongo-mongodb
